version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - "/AppendBenchmark" #AppendBenchmark.csproj
      - "/CounterBenchmark" #CounterBenchmark.csproj
      - "/CsvBenchmark" #CsvBenchmark.csproj
      - "/DictionaryBenchmark" #DictionaryBenchmark.csproj
      - "/ForBenchmark" #ForBenchmark.csproj
      - "/HttpClientBenchmark" #HttpClientBenchmark.csproj
      - "/HttpRequestBodyBenchmark" #HttpRequestBodyBenchmark.csproj
      - "/LinqBenchmark" #LinqBenchmark.csproj
      - "/ListBenchmark" #ListBenchmark.csproj
      - "/LoggingBenchmark" #LoggingBenchmark.csproj
      - "/ParallelBenchmark" #ParallelBenchmark.csproj
      - "/RailFenceCipherBenchmark" #RailFenceCipherBenchmark.csproj
      - "/ReplaceBenchmark" #ReplaceBenchmark.csproj
      - "/SealedBenchmark" #SealedBenchmark.csproj
      - "/SQLConnectionBenchmark" #SQLConnectionBenchmark.csproj
      - "/TupleBenchmark" #TupleBenchmark.csproj
    schedule:
      interval: "weekly"
      day: "sunday"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
